"use client";

import { Users, Shield } from "lucide-react";

export default function CustomersPage() {
  return (
    <div className="space-y-5 max-w-2xl">
      <div>
        <h1 className="text-xl font-bold text-text-primary tracking-tight">Customers</h1>
        <p className="text-sm text-text-secondary mt-0.5">Synthetic customer profiles — no real PII stored</p>
      </div>

      <div className="card-surface p-10 flex flex-col items-center gap-4 text-center">
        <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-brand-soft">
          <Users className="h-7 w-7 text-brand-primary" />
        </div>
        <div>
          <p className="text-base font-semibold text-text-primary">Synthetic customer data</p>
          <p className="text-sm text-text-secondary mt-1 max-w-md">
            All customer data in this system is generated by Faker. No real names, emails,
            phone numbers, or card data are ever stored. Customer IDs link to synthetic profiles
            with simulated payment history.
          </p>
        </div>
        <div className="flex items-center gap-2 text-xs text-success bg-success/10 px-3 py-1.5 rounded-full">
          <Shield className="h-3.5 w-3.5" />
          PII minimization · email_hash only · no real card data
        </div>
        <p className="text-xs text-text-tertiary max-w-sm">
          Customer-level data is accessible via Recovery Case detail pages.
          Navigate to <strong>Recovery Cases</strong> and click any case to see the associated customer context.
        </p>
      </div>
    </div>
  );
}
